version: "3.9"

services:
  db:
    image: postgres:16
    container_name: carhive-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - carhive-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: carhive-pgadmin
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend/Projet_Spring_Boot-CarHive
    container_name: carhive-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECURITY_JWT_EXPIRATION_TIME: ${SECURITY_JWT_EXPIRATION_TIME}
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend-angular:
    build:
      context: ./frontend/car-Front-end-Angular
    container_name: carhive-frontend-angular
    depends_on:
      - backend
    ports:
      - "4200:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  frontend-vue:
    build:
      context: ./frontend/car-hive-vueJs
    container_name: carhive-frontend-vue
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  carhive-data:

networks:
  app-network:
    driver: bridge
