version: "3.8"

services:
  jenkins:
    build: .
    container_name: jenkins-casc-confings
    user: root # 👈 Ajout 1 : donne tous les droits dans le conteneur
    privileged: true # 👈 Ajout 2 : autorise l'accès au démon Docker
    restart: always
    ports:
      - "8082:8080" # Jenkins UI
      - "50000:50000" # Agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    env_file:
      - ../.env

volumes:
  jenkins_home:
